unrest configuration file
---
/:
  GET:
    Content-Type: application/vnd.klarna.backoffice.accounts-v1+json
    Accept:
    __flow__:
      unrest_service: post
      unrest_service: get
      unrest_service: output
  POST: index_handler
  PATCH:
    __flow__:
      __flow__: PATCH_flow
      unrest_service:
        - output


__flows__:
    GET_flow:
      __flow__: SIMPLE_flow
      unrest_service: output
    PATCH_flow:
      unrest_service:
        - patch
      __flow__:
        - SIMPLE_flow
    AUTH_flow: unrest_handler
    SIMPLE_flow:
      unrest_service: get
    SINGLE_flow:
      __flow__: PATCH_flow
    MULTIPLE_flow:
      __flow__:
        - PATCH_flow
        - GET_flow
