unrest configuration file
---
- /:
    GET:
      Content-Type: application/vnd.klarna.backoffice.accounts-v1+json
      Accept:
      __flow__: &regular_flow
        unrest_service: output_post
        unrest_service: output_get
        unrest_service: do_output
    POST: index_handler
    PATCH:
      __flow__: *regular_flow
